#!/bin/zsh

selected=${1:-$(find ~/Documents/coding-projects/ ~/Documents/learning-dir/ ~/Documents/cloned-repos/ /home/ -mindepth 0 -maxdepth 1 -type d | fzf)}

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]]; then
  if ! tmux has-session -t=$selected_name 2>/dev/null; then
    command tmux new-session -A -s $selected_name -c "$selected"
  else
    command tmux attach -t $selected_name
  fi
else
  if ! tmux has-session -t=$selected_name 2>/dev/null; then
    command tmux new-session -A -ds $selected_name -c "$selected"
  fi
  command tmux switch-client -t $selected_name
fi

exit 0
